"""0046 — Wave-6 fund_economics: new grant/development fund programs.

Seeds fund_economics records for 18 new grant/fund programs added in
Wave-6 (grants3) covering Canada, Germany, Europe, USA, Israel, Australia,
Sweden, Burkina Faso, Portugal, Switzerland, Mexico, Norway, Finland,
UK, South Africa, Morocco, Argentina, Brazil.

Revision ID: 0046
Revises: 0045
"""
from __future__ import annotations

import uuid
from typing import Union

import sqlalchemy as sa
from alembic import op

revision: str = "0046"
down_revision: Union[str, None] = "0045"
branch_labels = None
depends_on = None


def _uid(key: str) -> uuid.UUID:
    return uuid.uuid5(uuid.NAMESPACE_DNS, f"frametax.fund_econ.wave6.{key}")


_FUND_DATA: dict[str, dict] = {
    "ca_bell_fund": {
        "is_repayable": False,
        "repayment_terms": None,
        "is_recoupable": False,
        "recoupment_terms": None,
        "has_equity_participation": False,
        "equity_participation_notes": None,
        "has_matching_requirement": True,
        "matching_notes": "Broadcast licence from Canadian broadcaster required. CAVCO Canadian content certification required.",
        "has_territorial_spend_requirement": True,
        "territorial_spend_notes": "Canadian production company and qualifying Canadian content required.",
        "eligible_formats": "digital,broadcast,interactive",
        "typical_max_award_usd": 300_000,
        "award_range_notes": "Typical grants CAD $50K–$400K per project (USD equivalent).",
        "is_competitive": True,
        "stackable_with_incentives": True,
        "stackability_notes": "Bell Fund grants are government-adjacent assistance; may reduce CPTC qualifying basis. Verify with CRA T4283.",
        "confidence_tier": "DISCOVERY",
        "notes": "Bell Fund — private broadcaster fund for Canadian digital/broadcast content. Not CMF.",
    },
    "ca_nsi_fund": {
        "is_repayable": False,
        "repayment_terms": None,
        "is_recoupable": False,
        "recoupment_terms": None,
        "has_equity_participation": False,
        "equity_participation_notes": None,
        "has_matching_requirement": False,
        "matching_notes": None,
        "has_territorial_spend_requirement": True,
        "territorial_spend_notes": "Canadian citizenship/residency required for creator eligibility.",
        "eligible_formats": "feature,documentary,series",
        "typical_max_award_usd": 25_000,
        "award_range_notes": "Typically CAD $5K–$25K development grants. Smaller scale than CMF.",
        "is_competitive": True,
        "stackable_with_incentives": True,
        "stackability_notes": "NSI grants are small development contributions; unlikely to trigger government assistance rules at this scale.",
        "confidence_tier": "DISCOVERY",
        "notes": "NSI National Screen Institute — training and development organization for Canadian creators.",
    },
    "de_berlinale_wcf": {
        "is_repayable": False,
        "repayment_terms": None,
        "is_recoupable": False,
        "recoupment_terms": None,
        "has_equity_participation": False,
        "equity_participation_notes": None,
        "has_matching_requirement": True,
        "matching_notes": "German co-production element required. Projects from Africa, Latin America, Middle East, Central Asia, Southeast Asia prioritized.",
        "has_territorial_spend_requirement": False,
        "territorial_spend_notes": None,
        "eligible_formats": "feature,documentary,animation",
        "typical_max_award_usd": 660_000,
        "award_range_notes": "EUR 50K–600K per project (USD ~$55K–$660K).",
        "is_competitive": True,
        "stackable_with_incentives": True,
        "stackability_notes": "WCF grants are not German government assistance in the tax credit sense. Stack with German DFFF and other incentives.",
        "confidence_tier": "DISCOVERY",
        "notes": "Berlinale World Cinema Fund — film festival development and production fund since 2004.",
    },
    "eu_torino_lab": {
        "is_repayable": False,
        "repayment_terms": None,
        "is_recoupable": False,
        "recoupment_terms": None,
        "has_equity_participation": False,
        "equity_participation_notes": None,
        "has_matching_requirement": True,
        "matching_notes": "International co-production element strongly encouraged. Creative Europe MEDIA co-supported.",
        "has_territorial_spend_requirement": False,
        "territorial_spend_notes": None,
        "eligible_formats": "feature,documentary",
        "typical_max_award_usd": 60_000,
        "award_range_notes": "EUR 5K–55K script development grants; FeatureLab production awards up to EUR 50K.",
        "is_competitive": True,
        "stackable_with_incentives": True,
        "stackability_notes": "TFL grants are small development contributions. No known interaction with national tax credit bases.",
        "confidence_tier": "DISCOVERY",
        "notes": "Torino Film Lab — European script development and lab programme for first/second features.",
    },
    "nl_idfa_fund": {
        "is_repayable": False,
        "repayment_terms": None,
        "is_recoupable": False,
        "recoupment_terms": None,
        "has_equity_participation": False,
        "equity_participation_notes": None,
        "has_matching_requirement": True,
        "matching_notes": "Broadcaster/distributor co-financing typically structured through IDFA Forum pitching.",
        "has_territorial_spend_requirement": False,
        "territorial_spend_notes": None,
        "eligible_formats": "documentary",
        "typical_max_award_usd": 200_000,
        "award_range_notes": "Broadcaster contributions from IDFA Forum typically $50K–$200K per project; not a formal grant programme.",
        "is_competitive": True,
        "stackable_with_incentives": True,
        "stackability_notes": "IDFA Forum commitments are co-financing, not grants; unlikely to reduce national credit bases.",
        "confidence_tier": "DISCOVERY",
        "notes": "IDFA Forum — Amsterdam documentary co-production market. Not a direct grant programme.",
    },
    "us_tribeca_fund": {
        "is_repayable": False,
        "repayment_terms": None,
        "is_recoupable": False,
        "recoupment_terms": None,
        "has_equity_participation": False,
        "equity_participation_notes": None,
        "has_matching_requirement": False,
        "matching_notes": None,
        "has_territorial_spend_requirement": False,
        "territorial_spend_notes": None,
        "eligible_formats": "feature,documentary",
        "typical_max_award_usd": 100_000,
        "award_range_notes": "Development grants $10K–$50K; Tribeca All Access awards up to $100K.",
        "is_competitive": True,
        "stackable_with_incentives": True,
        "stackability_notes": "Private foundation grants; no interaction with US state or international tax credits expected.",
        "confidence_tier": "DISCOVERY",
        "notes": "Tribeca Film Institute — NYC independent film grant programme.",
    },
    "il_jerusalem_fund": {
        "is_repayable": False,
        "repayment_terms": None,
        "is_recoupable": False,
        "recoupment_terms": None,
        "has_equity_participation": False,
        "equity_participation_notes": None,
        "has_matching_requirement": False,
        "matching_notes": None,
        "has_territorial_spend_requirement": False,
        "territorial_spend_notes": None,
        "eligible_formats": "feature,documentary",
        "typical_max_award_usd": 50_000,
        "award_range_notes": "Development grants $5K–$50K; lab selection includes international projects.",
        "is_competitive": True,
        "stackable_with_incentives": True,
        "stackability_notes": "Small development grants; no material interaction with Israeli or international tax credits.",
        "confidence_tier": "DISCOVERY",
        "notes": "Jerusalem International Film Lab — development grants linked to Jerusalem Film Festival.",
    },
    "au_miff_premiere": {
        "is_repayable": False,
        "repayment_terms": None,
        "is_recoupable": False,
        "recoupment_terms": None,
        "has_equity_participation": False,
        "equity_participation_notes": None,
        "has_matching_requirement": True,
        "matching_notes": "Australian content test applies. World or Australian premiere at MIFF required.",
        "has_territorial_spend_requirement": True,
        "territorial_spend_notes": "Australian majority production content required.",
        "eligible_formats": "feature",
        "typical_max_award_usd": 380_000,
        "award_range_notes": "Up to AUD $500K (~USD $380K at AUD/USD 0.76). Typically 1-3 films per cycle.",
        "is_competitive": True,
        "stackable_with_incentives": True,
        "stackability_notes": "MIFF grant is government-adjacent; may interact with Screen Australia assistance calculations. Verify with Screen Australia.",
        "confidence_tier": "DISCOVERY",
        "notes": "MIFF Premiere Fund — production grant for Australian features premiering at Melbourne IFF.",
    },
    "se_goteborg_fund": {
        "is_repayable": False,
        "repayment_terms": None,
        "is_recoupable": False,
        "recoupment_terms": None,
        "has_equity_participation": False,
        "equity_participation_notes": None,
        "has_matching_requirement": True,
        "matching_notes": "Nordic or international co-production element required for Nordic Co-production Summit.",
        "has_territorial_spend_requirement": False,
        "territorial_spend_notes": None,
        "eligible_formats": "feature,documentary",
        "typical_max_award_usd": 100_000,
        "award_range_notes": "Development support SEK 100K–1M (USD $10K–$100K range).",
        "is_competitive": True,
        "stackable_with_incentives": True,
        "stackability_notes": "Small development support; no material interaction with national incentives expected.",
        "confidence_tier": "DISCOVERY",
        "notes": "Göteborg Film Festival Nordic Co-production Summit grants for Nordic/international development.",
    },
    "bf_fespaco": {
        "is_repayable": False,
        "repayment_terms": None,
        "is_recoupable": False,
        "recoupment_terms": None,
        "has_equity_participation": False,
        "equity_participation_notes": None,
        "has_matching_requirement": True,
        "matching_notes": "African, Caribbean, or Pacific country producer required. Pan-African eligibility.",
        "has_territorial_spend_requirement": False,
        "territorial_spend_notes": None,
        "eligible_formats": "feature,documentary,short,animation",
        "typical_max_award_usd": 50_000,
        "award_range_notes": "Prizes and development grants vary; FESPACO Étalon Yennenga prize is prestige, not large cash.",
        "is_competitive": True,
        "stackable_with_incentives": True,
        "stackability_notes": "FESPACO grants are small; no known interaction with national tax incentives.",
        "confidence_tier": "DISCOVERY",
        "notes": "FESPACO Ouagadougou — Africa's largest film festival; development grants and ACP programme access.",
    },
    "pt_ica_coproduction": {
        "is_repayable": False,
        "repayment_terms": None,
        "is_recoupable": False,
        "recoupment_terms": None,
        "has_equity_participation": False,
        "equity_participation_notes": None,
        "has_matching_requirement": True,
        "matching_notes": "Portuguese minority co-producer required. Co-production treaty with origin country required.",
        "has_territorial_spend_requirement": True,
        "territorial_spend_notes": "Minimum Portuguese creative and expenditure participation per treaty terms.",
        "eligible_formats": "feature,documentary,animation",
        "typical_max_award_usd": 550_000,
        "award_range_notes": "EUR 50K–500K per project. ICA annual budget ~EUR 7-10M.",
        "is_competitive": True,
        "stackable_with_incentives": True,
        "stackability_notes": "ICA grants are Portuguese government assistance; may reduce Portuguese cash rebate qualifying basis.",
        "confidence_tier": "DISCOVERY",
        "notes": "ICA Portugal — selective production grants and international co-production support.",
    },
    "ch_foc_fund": {
        "is_repayable": False,
        "repayment_terms": None,
        "is_recoupable": False,
        "recoupment_terms": None,
        "has_equity_participation": False,
        "equity_participation_notes": None,
        "has_matching_requirement": True,
        "matching_notes": "Swiss co-producer required. Active co-production treaty with France, Germany, Austria, Italy, Canada.",
        "has_territorial_spend_requirement": True,
        "territorial_spend_notes": "Minimum Swiss creative/expenditure participation per treaty.",
        "eligible_formats": "feature,documentary,animation",
        "typical_max_award_usd": 330_000,
        "award_range_notes": "CHF 50K–300K (USD ~$55K–$330K). Cantonal additional support also available.",
        "is_competitive": True,
        "stackable_with_incentives": True,
        "stackability_notes": "Swiss FOC support does not typically interact with foreign national tax credit bases.",
        "confidence_tier": "DISCOVERY",
        "notes": "Swiss Federal Office of Culture (BAK/OFC) — international co-production support.",
    },
    "mx_imcine_grants": {
        "is_repayable": False,
        "repayment_terms": None,
        "is_recoupable": False,
        "recoupment_terms": None,
        "has_equity_participation": False,
        "equity_participation_notes": None,
        "has_matching_requirement": True,
        "matching_notes": "Mexican content and Mexican co-producer required. Co-production treaty access via Ibermedia.",
        "has_territorial_spend_requirement": True,
        "territorial_spend_notes": "Majority Mexican production required for FOPROCINE; FIDECINE more flexible.",
        "eligible_formats": "feature,documentary,animation,series",
        "typical_max_award_usd": 500_000,
        "award_range_notes": "FOPROCINE: MXN 1M–8M (~USD $50K–$400K). FIDECINE up to MXN 10M (~$500K).",
        "is_competitive": True,
        "stackable_with_incentives": True,
        "stackability_notes": "IMCINE grants are Mexican government assistance; may reduce EFICINE 10% credit basis.",
        "confidence_tier": "DISCOVERY",
        "notes": "IMCINE FOPROCINE/FIDECINE — Mexican government film development and production funds.",
    },
    "no_nfi_grants": {
        "is_repayable": False,
        "repayment_terms": None,
        "is_recoupable": False,
        "recoupment_terms": None,
        "has_equity_participation": False,
        "equity_participation_notes": None,
        "has_matching_requirement": True,
        "matching_notes": "Norwegian creative majority or significant Norwegian content required.",
        "has_territorial_spend_requirement": True,
        "territorial_spend_notes": "Norwegian spend required for Norwegian cultural content grants.",
        "eligible_formats": "feature,documentary,series,short,animation",
        "typical_max_award_usd": 1_100_000,
        "award_range_notes": "NOK 500K–10M+ (~USD $50K–$1M+). NFI cultural grants vary widely by project.",
        "is_competitive": True,
        "stackable_with_incentives": True,
        "stackability_notes": "NFI grants are Norwegian government assistance; may reduce 25% cash rebate qualifying basis.",
        "confidence_tier": "DISCOVERY",
        "notes": "Norwegian Film Institute — selective production grants (separate from 25% cash rebate).",
    },
    "fi_ses_grants": {
        "is_repayable": False,
        "repayment_terms": None,
        "is_recoupable": False,
        "recoupment_terms": None,
        "has_equity_participation": False,
        "equity_participation_notes": None,
        "has_matching_requirement": True,
        "matching_notes": "Finnish creative majority typically required. Co-production grants available with Eurimages/Nordic Fund.",
        "has_territorial_spend_requirement": True,
        "territorial_spend_notes": "Finnish cultural content and Finnish production company required.",
        "eligible_formats": "feature,documentary,short,animation,series",
        "typical_max_award_usd": 880_000,
        "award_range_notes": "EUR 100K–800K (~USD $110K–$880K). SES annual grants ~EUR 20-25M.",
        "is_competitive": True,
        "stackable_with_incentives": True,
        "stackability_notes": "SES grants are Finnish government assistance; may reduce Business Finland 25% rebate qualifying basis.",
        "confidence_tier": "DISCOVERY",
        "notes": "Finnish Film Foundation (SES) — selective production grants (separate from Business Finland rebate).",
    },
    "gb_creative_england": {
        "is_repayable": False,
        "repayment_terms": None,
        "is_recoupable": False,
        "recoupment_terms": None,
        "has_equity_participation": True,
        "equity_participation_notes": "Creative England may take equity positions in productions it invests in.",
        "has_matching_requirement": True,
        "matching_notes": "English regional (non-London) production benefit required.",
        "has_territorial_spend_requirement": True,
        "territorial_spend_notes": "Significant English regional spend required (Midlands, North, South West, East of England).",
        "eligible_formats": "feature,documentary,series,animation",
        "typical_max_award_usd": 500_000,
        "award_range_notes": "Grants and equity typically GBP 50K–£400K (~USD $65K–$500K).",
        "is_competitive": True,
        "stackable_with_incentives": True,
        "stackability_notes": "Creative England equity/grants may be UK government assistance; BFI Film Fund interaction rules apply (BFI equity not government assistance for AVEC, Creative England TBD).",
        "confidence_tier": "DISCOVERY",
        "notes": "Creative England — English regional film/TV fund (non-London). Production and development.",
    },
    "za_idc_film": {
        "is_repayable": True,
        "repayment_terms": "IDC provides development finance (concessional loans). Repayable from revenues.",
        "is_recoupable": True,
        "recoupment_terms": "IDC recoup position from distribution revenues after production cost recoupment.",
        "has_equity_participation": True,
        "equity_participation_notes": "IDC may take equity in productions it invests in.",
        "has_matching_requirement": True,
        "matching_notes": "South African content and employment creation required. IDC focuses on majority SA-controlled projects.",
        "has_territorial_spend_requirement": True,
        "territorial_spend_notes": "South African majority production and spend required.",
        "eligible_formats": "feature,documentary,series",
        "typical_max_award_usd": 2_000_000,
        "award_range_notes": "Concessional loans ZAR 5M–50M (~USD $300K–$3M). Equity up to ZAR 20M.",
        "is_competitive": True,
        "stackable_with_incentives": True,
        "stackability_notes": "IDC investment is government-related assistance; may reduce DTI/NFVF rebate qualifying basis.",
        "confidence_tier": "DISCOVERY",
        "notes": "IDC South Africa — Industrial Development Corporation creative industries loans and equity.",
    },
    "ma_ccm_avance": {
        "is_repayable": True,
        "repayment_terms": "Avance sur recettes is repayable from first receipts of the production.",
        "is_recoupable": True,
        "recoupment_terms": "CCM recoups from receipts after producer recoupment.",
        "has_equity_participation": False,
        "equity_participation_notes": None,
        "has_matching_requirement": True,
        "matching_notes": "Moroccan co-producer and cultural content test required.",
        "has_territorial_spend_requirement": True,
        "territorial_spend_notes": "Moroccan production company (SOTAP) and significant Morocco spend required.",
        "eligible_formats": "feature,documentary,animation",
        "typical_max_award_usd": 550_000,
        "award_range_notes": "MAD 500K–5M (~USD $50K–$550K). CCM annual fund approximately MAD 50M.",
        "is_competitive": True,
        "stackable_with_incentives": True,
        "stackability_notes": "CCM Avance sur Recettes is government assistance; may reduce CCM 20-30% cash rebate qualifying basis for the same production.",
        "confidence_tier": "DISCOVERY",
        "notes": "CCM Avance sur Recettes — development/production advance for Moroccan co-productions.",
    },
}


def upgrade() -> None:
    conn = op.get_bind()

    rows = []
    for slug, data in _FUND_DATA.items():
        result = conn.execute(
            sa.text("SELECT id FROM incentive_programs WHERE slug = :slug"),
            {"slug": slug},
        ).fetchone()
        if result is None:
            continue  # programme not yet seeded in DB; skip gracefully
        program_id = result[0]
        rows.append({
            "id": _uid(slug),
            "program_id": program_id,
            **data,
        })

    for row in rows:
        conn.execute(
            sa.text("""
                INSERT INTO fund_economics (
                    id, program_id,
                    is_repayable, repayment_terms,
                    is_recoupable, recoupment_terms,
                    has_equity_participation, equity_participation_notes,
                    has_matching_requirement, matching_notes,
                    has_territorial_spend_requirement, territorial_spend_notes,
                    eligible_formats, typical_max_award_usd,
                    award_range_notes, is_competitive,
                    stackable_with_incentives, stackability_notes,
                    confidence_tier, notes
                ) VALUES (
                    :id, :program_id,
                    :is_repayable, :repayment_terms,
                    :is_recoupable, :recoupment_terms,
                    :has_equity_participation, :equity_participation_notes,
                    :has_matching_requirement, :matching_notes,
                    :has_territorial_spend_requirement, :territorial_spend_notes,
                    :eligible_formats, :typical_max_award_usd,
                    :award_range_notes, :is_competitive,
                    :stackable_with_incentives, :stackability_notes,
                    :confidence_tier, :notes
                )
                ON CONFLICT (id) DO NOTHING
            """),
            row,
        )


def downgrade() -> None:
    conn = op.get_bind()
    ids = [_uid(slug) for slug in _FUND_DATA]
    for uid in ids:
        conn.execute(
            sa.text("DELETE FROM fund_economics WHERE id = :id"),
            {"id": uid},
        )
